# Generated by Django 5.2.17 on 2026-08-10 17:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile/')),
                ('instagram_url', models.URLField(blank=True)),
                ('behance_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('seo_title', models.CharField(max_length=70)),
                ('seo_description', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
