# Generated by Django 5.2.17 on 2026-08-10 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('file', models.FileField(upload_to='media_items/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('alt_text', models.CharField(max_length=200)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
