# Generated by Django 5.2.17 on 2026-08-21 22:20

import apps.media_items.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=apps.media_items.models.VideoAwareFileField(upload_to='media_items/'),
        ),
    ]
